version: "3.9" # compose format version, optional 
services:
  web:
    build: .
    ports:
      - "8080:8082"
    # environment:
    #   - APP_PORT
    #   - RUNTIME_SETUP
    #   - DB_DRIVER
    #   - SERVER_ADDRESS
    env_file:
      - app.env
    volumes:
      - ./logs:/app/logs
    links:
      - redis
  redis:
      image: redis:alpine